# Generated by Django 5.0.2 on 2024-02-20 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Album", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="telease_date",
            new_name="release_date",
        ),
    ]
