# Generated by Django 5.0.2 on 2024-03-29 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.date(2024, 3, 29)),
        ),
    ]
