# Generated by Django 5.0.2 on 2024-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
    ]
