# Generated by Django 5.0.2 on 2024-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_student_date_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_field',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
