# Generated by Django 5.0.2 on 2024-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_student_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_field',
            field=models.ImageField(default='img.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_field',
            field=models.EmailField(default='hello@gmail.com', max_length=254),
        ),
    ]
